In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib notebook
from sklearn import tree

In [2]:
df=pd.read_csv('weight-height.csv')
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
8550  Female  60.483946  110.565497
8551  Female  63.423372  129.921671
8552  Female  65.584057  155.942671
8553  Female  67.429971  151.678405
8554  Female  60.921791  131.253738

[8555 rows x 3 columns]

In [3]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le=LabelEncoder()

In [6]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [7]:
df.Gender = le.fit_transform(df['Gender'])

In [8]:
df

Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

[8555 rows x 3 columns]

In [9]:
df2=df.copy()

In [10]:
x=df.drop(['Gender'], axis=1)

In [11]:
y=df['Gender']

# Splitting the dataset into training and test set. 

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.30, random_state=1)

In [14]:
xtest

Height      Weight
7154  65.068038  160.800726
3258  70.824643  184.516688
2188  68.663594  184.262796
5609  65.987610  166.844114
3186  70.901461  200.466282
...         ...         ...
8004  58.963526  110.815421
7644  66.613529  148.605255
8521  67.895659  153.436481
957   69.031063  170.310122
233   71.476101  195.392618

[2567 rows x 2 columns]

In [15]:
xtrain

Height      Weight
1277  72.385301  189.165592
5361  60.960147  124.876796
5728  69.119292  168.864403
4276  68.271050  172.941248
3112  64.991405  144.551044
...         ...         ...
2895  71.382577  205.545795
7813  66.148829  152.749747
905   66.539812  175.093255
5192  66.563772  156.832191
235   70.555244  198.460249

[5988 rows x 2 columns]

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
le=LinearRegression()

In [18]:
le.fit(xtrain, ytrain)

LinearRegression()

In [19]:
le.predict([[1,72]])

array([1.63449411])

In [20]:
pred1=le.predict(xtest)

pred1

array([0.57393956, 0.73951033, 0.8207258 , ..., 0.34009443, 0.57491606,
       0.8940418 ])

# Accuracy -------------------------------

In [21]:
le.score(xtest, ytest)

0.6527835049117745

In [22]:
from sklearn.metrics import mean_absolute_error

In [23]:
mae= mean_absolute_error(ytest, le.predict(xtest))

In [24]:
mae

0.23503850687795877

In [25]:
from sklearn.metrics import mean_squared_error, r2_score

In [26]:
mse=mean_squared_error(ytest, le.predict(xtest))

In [27]:
mse

0.08405293100951133

In [28]:
r2_score(ytest,le.predict(xtest))

0.6527835049117745

# Apply KNN Regressor

In [29]:
df.shape

(8555, 3)

In [30]:
xtrain.shape

(5988, 2)

In [31]:
from sklearn.neighbors import KNeighborsRegressor

In [32]:
knn= KNeighborsRegressor(n_neighbors = 100)

In [33]:
knn.fit(xtrain, ytrain)

KNeighborsRegressor(n_neighbors=100)

In [35]:
knn.predict([[60.483946, 110.565497]]) #-------------------------

array([0.01])

In [36]:
knn.score(xtest,ytest)

0.7566539808545851

In [ ]:
pred2 =knn.predict(xtest)

In [ ]:
pred2

In [ ]:
mean_squared_error(ytest,pred2)

In [ ]:
r2_score(ytest,pred2)

In [ ]:
mse=mean_squared_error(ytest, pred2)

In [ ]:
mse